# PHASE 3 CHECK THE TABLE INTEGRITY 
Goal

Before joining tables, answer one question:

Can I trust the relationships between my tables?

In [2]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_colwidth", None)

In [3]:
customers = pd.read_csv("c:/Users/Steve/Desktop/datascience-project1/project/data/raw/olist_customers_dataset.csv")
orders = pd.read_csv("c:/Users/Steve/Desktop/datascience-project1/project/data/raw/olist_orders_dataset.csv")
order_items = pd.read_csv("c:/Users/Steve/Desktop/datascience-project1/project/data/raw/olist_order_items_dataset.csv")
payments = pd.read_csv("c:/Users/Steve/Desktop/datascience-project1/project/data/raw/olist_order_payments_dataset.csv")
products = pd.read_csv("c:/Users/Steve/Desktop/datascience-project1/project/data/raw/olist_products_dataset.csv")
reviews = pd.read_csv("c:/Users/Steve/Desktop/datascience-project1/project/data/raw/olist_order_reviews_dataset.csv")
sellers = pd.read_csv("c:/Users/Steve/Desktop/datascience-project1/project/data/raw/olist_sellers_dataset.csv")
geolocation = pd.read_csv("c:/Users/Steve/Desktop/datascience-project1/project/data/raw/olist_geolocation_dataset.csv")
translation = pd.read_csv("c:/Users/Steve/Desktop/datascience-project1/project/data/raw/product_category_name_translation.csv")

In [4]:
datasets = {
    "customers": customers,
    "orders": orders,
    "order_items": order_items,
    "payments": payments,
    "products": products,
    "reviews": reviews,
    "sellers": sellers,
    "geolocation": geolocation,
    "translation": translation
}

### Validation 1. Question

Is every orders.customer_id present inside customers.customer_id?

In [5]:
missing_customers = orders[
    ~orders["customer_id"].isin(customers["customer_id"])
]

print("Missing Customers:", len(missing_customers))
missing_customers.head()

Missing Customers: 0

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date]
Index: []

### Validation 2. Question
Does every Order Item belong to an Order?

In [6]:

missing_orders = order_items[
    ~order_items["order_id"].isin(orders["order_id"])
]

print("Missing Orders:", len(missing_orders))
missing_orders.head()

Missing Orders: 0

Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value]
Index: []

### Validation 3

Does every Product exist?

In [7]:

missing_products = order_items[
    ~order_items["product_id"].isin(products["product_id"])
]

print("Missing Products:", len(missing_products))
missing_products.head()

Missing Products: 0

Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value]
Index: []

### Validation 4
Does every Seller exist?

In [8]:

missing_sellers = order_items[
    ~order_items["seller_id"].isin(sellers["seller_id"])
]

print("Missing Sellers:", len(missing_sellers))
missing_sellers.head()

Missing Sellers: 0

Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value]
Index: []

### Validation 5
Does every Payment belong to an Order?

In [9]:
missing_payment_orders = payments[
    ~payments["order_id"].isin(orders["order_id"])
]

print("Missing Payment Orders:", len(missing_payment_orders))
missing_payment_orders.head()

Missing Payment Orders: 0

Empty DataFrame
Columns: [order_id, payment_sequential, payment_type, payment_installments, payment_value]
Index: []

### Validation 6
Does every Review belong to an Order?

In [10]:

missing_review_orders = reviews[
    ~reviews["order_id"].isin(orders["order_id"])
]

print("Missing Review Orders:", len(missing_review_orders))
missing_review_orders.head()

Missing Review Orders: 0

Empty DataFrame
Columns: [review_id, order_id, review_score, review_comment_title, review_comment_message, review_creation_date, review_answer_timestamp]
Index: []